package: types

import:
  - github.com/ethereum/go-ethereum/common
  - github.com/ethereum/go-ethereum/common/hexutil
  - time

json-package: encoding/json

scalarMapper:
  Address: common.Hash
  AssetId: common.Hash
  BlockId: common.Hash
  Boolean: bool
  Bytes32: common.Hash
  ContractId: common.Hash
  Float: float64
  HexString: hexutil.Bytes
  ID: string
  Int: int32
  Nonce: string
  Salt: string
  Signature: hexutil.Bytes
  String: string
  Tai64Timestamp: time.Time
  TransactionId: common.Hash
  TxPointer: string
  U8: uint8
  U32: uint32
  U64: uint64
  UtxoId: hexutil.Bytes
